#!/usr/bin/env python3
"""Final prompt set of the long run (author, 2026-09-19: "half fineweb edu half self-generated by us"): for the reading classes A, B, C take the
8 best corpus prompts (FineWeb-Edu, the model's training distribution) and the 8 best SELF-WRITTEN ones (texts written for this run, in no
training set); class D (standard short openers) is the demo's own prompt pool, all self-written. Ranking inside each pool = the selector's
(nearTies, -distinct2, msHiMax) after its hard filters. usage: prompt_select_combine.py <corpus prefix> <self prefix> <out prefix>"""
import json, sys
corp, selfp, out = sys.argv[1:4]
STOP = set("the a an of and to in is are was were be been it its that this these those for on with as by at from or not but which who their his her they he she we you i has have had can will would may also more than into over about such other some most many one two".split())
def quality(r):
    """word-level text quality of the generated continuation (2026-09-19, author: prompts 'where repetition will not occur'):
    rep6 = a 6-word sequence occurs twice; distinctW = distinct / total words; topShare = share of the most frequent non-stop word;
    listy = share of lines that are list items or of words that are bare separators."""
    w = r["text"].split(); seen = set(); rep6 = False
    for i in range(len(w) - 5):
        g = tuple(w[i:i + 6])
        if g in seen: rep6 = True; break
        seen.add(g)
    lw = [x.lower().strip(".,;:!?()\"'") for x in w]; cw = [x for x in lw if x and x not in STOP]
    from collections import Counter
    top = (Counter(cw).most_common(1)[0][1] / max(len(cw), 1)) if cw else 1.0
    lines = [l for l in r["text"].split("\n") if l.strip()]; listy = sum(1 for l in lines if l.lstrip().startswith(("-", "*", "•")) or l.lstrip()[:2].rstrip(".").isdigit()) / max(len(lines), 1)
    return {"rep6": rep6, "distinctW": round(len(set(lw)) / max(len(lw), 1), 3), "topShare": round(top, 3), "listy": round(listy, 3), "newlines": r["text"].count("\n")}
def ranked(prefix):
    rows = [json.loads(l) for l in open(prefix + ".scores.jsonl")]
    for r in rows: r.update(quality(r))
    ok = [r for r in rows if r["newtonWorst"] < 1e-6 and r["msHiMax"] < 30.0 and not r["loop"]]
    good = [r for r in ok if not r["rep6"] and r["topShare"] <= 0.10 and r["listy"] <= 0.34 and "<|endoftext|>" not in r["text"]
            and "\r" not in r["text"] and r["newlines"] <= 10 and not any(len(w) > 3 and w.isupper() for w in r["text"].split()[:400] if w.isalpha()) ]   # no old-book formatting, no ALL-CAPS headings
    print(f"{prefix.split('/')[-1]}: {len(rows)} scored, {len(ok)} pass the hard filters, {len(good)} of those pass the text-quality filters (no repeated 6-word sequence, top content word <= 10 %, lists <= 1/3 of lines, <= 10 newlines, no carriage returns, no ALL-CAPS words)")
    good.sort(key=lambda r: (r["nearTies"], -r["distinctW"], r["msHiMax"])); return good
C, S = ranked(corp), ranked(selfp); pick = {}
for k in "ABC":
    pick[k] = [dict(r, source="FineWeb-Edu") for r in [r for r in C if r["class"] == k][:8]] + [dict(r, source="written for this run") for r in [r for r in S if r["class"] == k][:8]]
    # alternate the two sources inside the class
    a, b = pick[k][:8], pick[k][8:]; pick[k] = [x for pair in zip(a, b) for x in pair]
pick["D"] = [dict(r, source="demo prompt pool (self-written)") for r in [r for r in C if r["class"] == "D"][:16]]
order = [pick[k][i] for i in range(16) for k in "ABCD"]
lab = {"A": "A long reading", "B": "B medium reading", "C": "C short reading", "D": "D standard short"}
open(out + ".txt", "w").write("".join(r["prompt"] + "\n" for r in order))
json.dump({str(i): f"{lab[r['class']]} / {r['source']}" for i, r in enumerate(order)}, open(out + ".txt.classes.json", "w"))
json.dump({str(i): r["text"] for i, r in enumerate(order)}, open(out + ".txt.outputs.json", "w"))
with open(out + ".scores.jsonl", "w") as f:
    for r in order: f.write(json.dumps(r) + "\n")
rep = ["# Final prompt set of the long run: half corpus, half self-written (plaintext emulation, 172 ticks)", "",
       "| lane | class | source | prompt tokens | generated in 172 ticks | nearTies | minMargin | msHiMax (site) | max abs state | distinct words | top word share | prompt (start) | plaintext continuation (start) |", "|---|---|---|---|---|---|---|---|---|---|---|---|---|"]
for i, r in enumerate(order):
    rep.append(f"| {i} | {r['class']} | {r['source']} | {r['promptTokens']} | {r['genTokens']} | {r['nearTies']} | {r['minMargin']:.4f} | {r['msHiMax']:.2f} ({r['msHiSite']}) | {r['maxAbsState']:.2f} | {r['distinctW']} | {r['topShare']} | {r['prompt'][:60]!r} | {r['text'][:80]!r} |")
def line(name, rows): return f"- {name}: n {len(rows)}, prompt tokens {min(r['promptTokens'] for r in rows)}-{max(r['promptTokens'] for r in rows)}, min generated {min(r['genTokens'] for r in rows)}, loops {sum(r['loop'] for r in rows)}, near-tie ticks {sum(r['nearTies'] for r in rows)} (max per lane {max(r['nearTies'] for r in rows)}), max ms/hi {max(r['msHiMax'] for r in rows):.1f}, max abs state {max(r['maxAbsState'] for r in rows):.2f}"
rep += ["", line("ALL 64", order), line("corpus half (24)", [r for r in order if r["source"] == "FineWeb-Edu"]), line("self-written reading half (24)", [r for r in order if r["source"] == "written for this run"]), line("class D (16)", pick["D"])]
open(out + ".report.md", "w").write("\n".join(rep) + "\n"); print("\n".join(rep[-4:]))
